[build]
  command = "nodemon backend/server.js"  # Adjust this based on your actual build script
  functions = "functions"  # Change this to the directory where your serverless functions are located

[[plugins]]
  package = "./netlify-plugin-no-more-404"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
